<?php
error_reporting(E_ALL);
ini_set('display_errors', 'On');

$content = "<?php\n";
$content .= "if (!isset(\$_SESSION))  {\n";
$content .= "    session_start();\n";
$content .= "}\n";
$content .= "\n";
$content .= "if (\$_SESSION[\"login\"] != \"true\") {\n";
$content .= "    header(\"Location:login.php\");\n";
$content .= "    \$_SESSION[\"error\"] = \"<h1 style='color:red;'>You don't have privileges to see this page.</h1>\";\n";
$content .= "    exit;\n";
$content .= "}\n";
$content .= "?>\n";
$content .= "\n";
$content .= "include_once('settings.php');\n";
$content .= "\n";
$content .= "<!DOCTYPE html>\n";
$content .= "<html lang=\"de\">\n";
$content .= "<head>\n";
$content .= "	<meta charset=\"utf-8\" />\n";
$content .= "	<title>Ephemere Filme: Nationalsozialismus in &Ouml;sterreich</title>\n";
$content .= "	<!-- basis css -->\n";
$content .= "	<!-- eF EditorP css -->\n";
$content .= "	<link id=\"mainstylesheet\" rel=\"stylesheet\" type=\"text/css\" href=\"_css/eFEditorV.css\" media=\"screen\" />\n";
$content .= "	<link id=\"mainstylesheet\" rel=\"stylesheet\" type=\"text/css\" href=\"_css/eFEditorVResourcesInMovies_Movie.css\" media=\"screen\" />\n";
$content .= "	<!-- /eF EditorP css -->\n";
$content .= "	<!-- jquery ui tools-->\n";
$content .= "	<link rel=\"stylesheet\" type=\"text/css\" href=\"_css/smoothness/jquery-ui-1.8.17.custom.css\" media=\"screen\" />\n";
$content .= "	<!-- /basis css -->\n";
$content .= "	<!-- jquery -->\n";
$content .= "		<!-- jquery base-->\n";
$content .= "		<script>\n		var storeURL = '".$storeURL."';\n		</script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQBaseUI/jquery-1.7.1.min.js\"></script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQBaseUI/jquery-ui-1.8.17.custom.min.js\"></script>\n";
$content .= "		<!-- <script type=\"text/javascript\" src=\"_js/jQBaseUI/jquery.ui.touch-punch.min\"></script>-->\n";
$content .= "		<!-- jquery ui tools-->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQBaseUI/jquery.tools.min.js\"></script>\n";
$content .= "		<!-- jquery media-->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQMedia/jquery.media.core.js\"></script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQMedia/jquery.media.timeline.js\"></script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQMedia/plugins/syncwith.js\"></script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQMedia/plugins/tocanvas.js\"></script>\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQMedia/plugins/tracks.js\"></script>\n";
$content .= "		<!-- jquery Editable -->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQEditable/jquery.jeditable.mini.js\"></script>\n";
$content .= "		<!-- jquery Forms -->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQForms/jquery.form.js\"></script>\n";
$content .= "		<!-- jquery ScrollTo -->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/jQScrollTo/jquery.scrollTo-1.4.2-min.js\"></script>\n";
$content .= "	<!-- /jquery -->\n";
$content .= "	<!-- OpenLayers -->\n";
$content .= "	 <script type='text/javascript' src='http://www.openlayers.org/api/OpenLayers.js'></script>\n";
$content .= "	<!-- /OpenLayers -->\n";
$content .= "	<!-- eF JS -->\n";
$content .= "		<script type=\"text/javascript\" src=\"_js/eFEditorV/eFEditorV.js\"></script>\n";
$content .= "	<!-- /eF JS -->\n";
$content .= "</head>\n";
$content .= "<body data-remip=\"<?php echo \$_SERVER[\"REMOTE_ADDR\"]; ?>\">\n";
$content .= "<!-- eF Preview Container -->\n";
$content .= "<div id=\"eFPreviewsContainer\">\n";
$content .= "	<div class=\"eFPreviewsContainerSelect\" id=\"eFPreviewsContainerP1\" data-demo=\"D1\">1</div>\n";
$content .= "	<div class=\"eFPreviewsContainerSelect\" id=\"eFPreviewsContainerP2\" data-demo=\"D2\">2</div>\n";
$content .= "	<div id=\"eFPreviewsContainerClose\">X</div>\n";
$content .= "	<div id=\"eFPreviewsContainerContent\"></div>\n";
$content .= "</div>\n";
$content .= "<!-- eF Preview Container -->\n";
$content .= "<!-- eF ReSources Container -->\n";
$content .= "<div id=\"eFResourcesContainer\">\n";
$content .= "	<div id=\"eFResourcesContainerContent\"></div>\n";
$content .= "	<div id=\"eFResourcesContainerClose\">X</div>\n";
$content .= "</div>\n";
$content .= "<!-- /eF ReSources Container -->\n";
$content .= "<!-- eF eFResourcesPreviewWindowContainer Container -->\n";
$content .= "<div id=\"eFResourcesPreviewWindowContainer\">\n";
$content .= "	<div id=\"eFResourcesPreviewWindowContainerContent\"></div>\n";
$content .= "	<div id=\"eFResourcesPreviewWindowContainerClose\">X</div>\n";
$content .= "</div>\n";
$content .= "<!-- /eF eFResourcesPreviewWindowContainer Container -->\n";
$content .= "<!-- eF Config Container -->\n";
$content .= "<div id=\"eFConfigContainer\">\n";
$content .= "	<div id=\"eFConfigContainerContent\"></div>\n";
$content .= "	<div id=\"eFConfigContainerClose\">X</div>\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "<!-- /eF Config Container -->\n";
$content .= "\n";
$content .= "<!-- eF ReSourcesFromMovie Container -->\n";
$content .= "<div id=\"eFReSourcesFromMovieContainer\" data-formid=\"\">\n";
$content .= "	<div id=\"eFReSourcesFromMovieContainerContent\"></div>\n";
$content .= "	<div id=\"eFReSourcesFromMovieContainerTR\"><div id=\"eFReSourcesFromMovieContainerClose\">X</div></div>\n";
$content .= "	<div id=\"eFReSourcesFromMovieContainerSeeThrough\"></div>\n";
$content .= "	<div id=\"eFReSourcesFromMovieContainerBR\"></div>\n";
$content .= "	\n";
$content .= "</div>\n";
$content .= "<!-- /eF ReSourcesFromMovie Container -->\n";
$content .= "<div id=\"eFDelQuestion\"></div>\n";
$content .= "<!-- eF Header -->\n";
$content .= "<div id=\"eFMovieSelectContainer\">\n";
$content .= "	<div class=\"eFMoviesHeadline\">Select Movie</div>\n";
$content .= "	<div id=\"eFMoviesSelectListContainer\">\n";
$content .= "	<table>\n";
$content .= "	\n";
$content .= "	<?php include (\"_ajax/eFEditorVMovieList.php\"); ?>\n";
$content .= "	\n";
$content .= "	</table>\n";
$content .= "	</div>\n";
$content .= "</div>\n";
$content .= "<div id=\"eFHeader\">\n";
$content .= "	 <div id=\"eFLogout\"><a href=\"login.php\" title=\"Logout\">Logout</a></div>\n";
$content .= "                        <div id=\"eFCurrUser\">\n";
$content .= "                            Current User: <?php echo \$_SESSION[\"uname\"]; ?> (<span id=\"eFUserNik\"><?php echo \$_SESSION[\"unik\"]; ?></span>)\n";
$content .= "                        </div>\n";
$content .= "	<div id=\"eFOpenArea\">\n";
$content .= "		<div id=\"eFPreviewOpen\" class=\"eFOpen\" onclick=\"\">Preview</div>\n";
$content .= "<?php\n";
$content .= "require_once(\"includes/functions.php\");\n";
$content .= "require_once(directoryAboveWebRoot().\"/db_con.php\");\n";
$content .= "\$anfrage_ULDI = \"SELECT * FROM eFilm_Config_Users WHERE ID_C_Users='\".\$_SESSION[\"efuid\"].\"';\";\n";
$content .= "\$ergebnis_ULDI = mysqli_query(\$localDatabase, \$anfrage_ULDI);\n";
$content .= "\$trefferzahl_ULDI=mysqli_num_rows(\$ergebnis_ULDI);\n";
$content .= "\$row_ULDI = mysqli_fetch_array(\$ergebnis_ULDI);\n";
$content .= "\n";
$content .= "if (\$row_ULDI['RIGHTS_Resources'] == \"NONE\") {\n";
$content .= "    echo \"\";\n";
$content .= "} else {\n";
$content .= "    echo '<div id=\"eFResourcesOpen\" class=\"eFOpen\" onclick=\"\">Resources</div>';\n";
$content .= "    echo '<div id=\"eFLog\" class=\"eFOpen\" onclick=\"\">Log</div>';\n";
$content .= "    echo '<div id=\"eFPublish\" class=\"eFOpen\" onclick=\"\">Publish</div>';\n";
$content .= "}\n";
$content .= "\n";
$content .= "if (\$row_ULDI['RIGHTS_Config'] == \"NONE\") {\n";
$content .= "    echo \"\";\n";
$content .= "} else {\n";
$content .= "    echo '<div id=\"eFConfigOpen\" class=\"eFOpen\" onclick=\"\">Config</div>';\n";
$content .= "}\n";
$content .= "?>\n";
$content .= "\n";
$content .= "	</div>\n";
$content .= "<div id=\"eFLogoOpen\" onclick=\"\"></div>\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "<!-- /eF Header -->\n";
$content .= "<div id=\"contentConatiner\">\n";
$content .= "<!-- eF Movie Container HTML -->\n";
$content .= "<div id=\"eFMovieContainer\" data-efposmodus=\"movie\">\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "<!-- /eF Movie Container HTML -->\n";
$content .= "<!-- eF Annotations Container HTML -->\n";
$content .= "<div id=\"eFMovieAnnotationsContainer\">\n";
$content .= "\n";
$content .= "<div id=\"eFMovieAnnotationsContainerMovieID\">\n";
$content .= "	<!--<div id=\"eFMovieMovieID\">Movie ID</div> -->\n";
$content .= "	<!--<div id=\"eFMovieMovieIDopenAnotSelect\">+</div> -->\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "\n";
$content .= "<div id=\"eFMovieAnnotationsContainerScenarioSelect\">\n";
$content .= "	<div id=\"eFMovieAnnotationsContainerScenarioSelectM\">\n";
$content .= "		<div class=\"eFSCMButton\" id=\"eFSCMCoverage\" title=\"Coverage\">C</div>\n";
$content .= "		<div class=\"eFSCMButton\" id=\"eFSCMSubject\" title=\"Subject\">S</div>\n";
$content .= "		<div class=\"eFSCMButton\" id=\"eFSCMLanguage\" title=\"Language\">L</div>\n";
$content .= "		<div class=\"eFSCMButton\" id=\"eFSCMRelation\" title=\"Relation\">R</div>\n";
$content .= "		<div class=\"eFSCMButton\" id=\"eFSCMDescription\" title=\"Description\">D</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectS\" id=\"eFMovieAnnotationsContainerScenarioSelectSCoverage\">\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSSpatial\" title=\"Spatial\">S</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSTemporal\" title=\"Temporal\">T</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectS\" id=\"eFMovieAnnotationsContainerScenarioSelectSSubject\">\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSPerson\" title=\"Person\">P</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSOrganization\" title=\"Organization\">O</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSHistoricEvent\" title=\"Historic Event\">H</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectS\" id=\"eFMovieAnnotationsContainerScenarioSelectSLanguage\">\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSLanguage\" title=\"Language\">L</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectS\" id=\"eFMovieAnnotationsContainerScenarioSelectSRelation\">\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSRelation\" title=\"Relation\">R</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectS\" id=\"eFMovieAnnotationsContainerScenarioSelectSDescription\">\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSNumbering\" title=\"Numbering\">N</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSImageContent\" title=\"Image Content\">C</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSFilmAnalysis\" title=\"Film Analysis\">A</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSInterpretation\" title=\"Interpretation\">I</div>\n";
$content .= "		<div class=\"eFSCDButton\" id=\"eFSCSEducationalRemarks\" title=\"Educational Remarks\">P</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDCoverageSpatial\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDLocationN\" title=\"Location (Name)\">Location (Name)</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDLocationG\" title=\"Location (Geoinfo)\">Location (Geoinfo)</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDLandmark\" title=\"Landmark\">Landmark</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDCoverageTemporal\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDDate\" title=\"Date\">Date</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDSubjectPerson\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDPerson\" title=\"Person\">Person</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDSubjectOrganization\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDOrganisation\" title=\"Organization\">Organization</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDSubjectHistoricEvent\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCDHistoricEvent\" title=\"Historic Event\">Historic Event</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDLanguage\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSLanguage\" title=\"Language\">Language</div>\n";
$content .= "	</div>\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDRelation\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSRelation\" title=\"Relation\">Relation</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDDescriptionNumbering\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSSequenceNumber\" title=\"Sequence Number\">Sequence Number</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSSceneNumber\" title=\"Scene Number\">Scene Number</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSShotNumber\" title=\"Shot Number\">Shot Number</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSReelNumber\" title=\"Reel Number\">Reel Number</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDDescriptionImageContent\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSSpacialType\" title=\"Spacial Type\">Spacial Type</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSSpacialUse\" title=\"Spacial Use\">Spacial Use</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSPersonsNumber\" title=\"Persons Number\">Persons Number</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSPersonsGender\" title=\"Persons Gender\">Persons Gender</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSPersonsAge\" title=\"Persons Age\">Persons Age</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSPersonsAction\" title=\"Persons Action\">Persons Action</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSVisualEventType\" title=\"Visual Event Type\">Visual Event Type</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSVisualEvent\" title=\"Visual Event\">Visual Event</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSAudioEventType\" title=\"Audio Event Type\">Audio Event Type</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSAudioEvent\" title=\"Audio Event\">Audio Event</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSIntertitleTranscript\" title=\"Intertitle Transcript\">Intertitle Transcript</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSWrittenElementsTranscript\" title=\"Written Elements Transcript\">Written Elements Transcript</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSWrittenElementsLanguage\" title=\"Written Elements Language\">Written Elements Language</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSSpokenElementsTranscript\" title=\"Spoken Elements Transcript\">Spoken Elements Transcript</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSPunctum\" title=\"Punctum\">Punctum</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDDescriptionFilmAnalysis\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSShotType\" title=\"Shot Type\">Shot Type</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSCameraPosition\" title=\"Camera Position\">Camera Position</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSEditing\" title=\"Editing\">Editing</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDDescriptionInterpretation\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSAmateurFilmCharacteristics\" title=\"Amateur Film Characteristics\">Amateur Film Characteristics</div>\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSIntention\" title=\"Intention\">Intention</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "	<div class=\"eFMovieAnnotationsContainerScenarioSelectD\" id=\"eFMovieAnnotationsContainerScenarioSelectDDescriptionEducationalRemarks\">\n";
$content .= "		<div class=\"eFSCDetail\" id=\"eFSCSEducationalRemarks\" title=\"Educational Remarks\">Educational Remarks</div>\n";
$content .= "	</div>\n";
$content .= "	\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "<div id=\"eFMovieAnnotationsContainerINOUTContainer\">\n";
$content .= "	<div id=\"eFMovieAnnotationsContainerINOUT\">\n";
$content .= "		<span id=\"eFAFormINGET\">IN:</span> <input type=\"text\" name=\"IN\" id=\"eFAFormIN\" value=\"\">\n";
$content .= "		<span id=\"eFAFormOUTGET\">OUT:</span> <input type=\"text\" name=\"IN\" id=\"eFAFormOUT\" value=\"\">\n";
$content .= "		<span id=\"eFMovieAnnotationsContainerINOUTPlay\"></span>\n";
$content .= "	</div>\n";
$content .= "	<div id=\"eFMovieAnnotationsContainerINOUTPlay\"></div>\n";
$content .= "</div>\n";
$content .= "<div id=\"eFMovieAnnotationsContainerForms\">\n";
$content .= "	<div id=\"eFMovieAnnotationsContainerFormsPop\">\n";
$content .= "		<div id=\"eFMovieAnnotationsContainerFormsPopContent\"></div>\n";
$content .= "		<div id=\"eFMovieAnnotationsContainerFormsPopClose\">close</div>\n";
$content .= "	</div>\n";
$content .= "</div>\n";
$content .= "<div id=\"eFMovieAnnotationsEditBOOL\">JA</div>\n";
$content .= "<div id=\"eFMovieAnnotationsContainerANList\">\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "<!-- /eF Annotations Container HTML -->\n";
$content .= "\n";
$content .= "\n";
$content .= "\n";
$content .= "<!-- eF Movie Container HTML -->\n";
$content .= "<!-- /eF Movie Container HTML -->\n";
$content .= "<!-- eF Movie Timeline Container HTML -->\n";
$content .= "<div id=\"eFTimelineContainer\">\n";
$content .= "	<table class=\"eFTimelineContainerTable\">\n";
$content .= "		<thead>\n";
$content .= "			<tr id=\"eFTimelineContainerTableFrameNumbers\">\n";
$content .= "			<th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>\n";
$content .= "			<th id=\"eFTimelineContainerTableIN\"><img id=\"efTLCIN\" alt=\"in\" src=\"_img/in.png\" width=\"14\" height=\"14\"/></th><th id=\"eFTimelineContainerTableActual\">&nbsp;</th><th id=\"eFTimelineContainerTableOUT\"><img id=\"efTLCOUT\" alt=\"out\" src=\"_img/out.png\" width=\"14\" height=\"14\"/></th>\n";
$content .= "			<th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>\n";
$content .= "			</tr>\n";
$content .= "		</thead>\n";
$content .= "		<tbody>\n";
$content .= "			<tr id=\"eFTimelineContainerTableFramePics\">\n";
$content .= "			<td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			<td colspan=\"3\" id=\"eFTimelineContainerAFrame\"><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			<td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			</tr>\n";
$content .= "		</tbody>\n";
$content .= "	</table>\n";
$content .= "</div>\n";
$content .= "<!-- /eF Movie Timeline Container HTML -->\n";
$content .= "<!-- eF Movie Controls Container HTML -->\n";
$content .= "<div id=\"eFMovieControlsContainerSloMo\">\n";
$content .= "<div id=\"efMoviePlaybuttonsSloMoChoose\" class=\"efMoviePlaybuttonsC\">\n";
$content .= "		<select id=\"eFSloMoSpeedChooser\">\n";
$content .= "			<option value=\"1000\">1</option>\n";
$content .= "			<option value=\"500\">2</option>\n";
$content .= "			<option value=\"333\">3</option>\n";
$content .= "			<option value=\"250\">4</option>\n";
$content .= "		</select>\n";
$content .= "	</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsSloMoB\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsSloMoF\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "</div>\n";
$content .= "<div id=\"eFMovieControlsContainer\">\n";
$content .= "	<!-- <div id=\"efMoviePlaybuttonsPlayPauseB\" class=\"efMoviePlaybuttons\">&emsp;</div> -->\n";
$content .= "	<div id=\"efMoviePlaybuttonsPlayPauseF\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div id=\"efMoviePlaybuttonsStart\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsEnd\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">6</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">12</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">16</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">18</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">20</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">22</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">24</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">25</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">36</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">48</div>\n";
$content .= "</div>\n";
$content .= "<!-- /eF Movie Controls Container HTML -->\n";
$content .= "<!-- eF Movie RangeInput Container HTML -->\n";
$content .= "<div id=\"eFMovieRangeInputContainer\">\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "<!-- /eF Movie RangeInput Container HTML -->\n";
$content .= "<!-- eF Movie Timecodes Container HTML -->\n";
$content .= "<div id=\"eFMovieTimecodesContainer\">\n";
$content .= "	<div class=\"eFTimecodesHeadline\">Timing</div>\n";
$content .= "	<table class=\"timecodetable\">\n";
$content .= "		<tr>\n";
$content .= "			<th><div class=\"eFMovieTimecodesContainerHeads\">Frames</div></th><th><div class=\"eFMovieTimecodesContainerHeads\">SMPTE</div></th>\n";
$content .= "		</tr>\n";
$content .= "		<tr>\n";
$content .= "			<td id=\"eFControlDataMovieTimecodeContainerFPS\">000000</td><td id=\"eFControlDataMovieTimecodeContainerSMPTE\">00:00:00:00</td>\n";
$content .= "		</tr>\n";
$content .= "		<tr>\n";
$content .= "			<th><div class=\"eFMovieTimecodesContainerHeads\">HH:MM:SS</div></th><th><div class=\"eFMovieTimecodesContainerHeads\">FLOAT</div></th>\n";
$content .= "		</tr>\n";
$content .= "		<tr>\n";
$content .= "			<td id=\"eFControlDataMovieTimecodeContainerHHMMSS\">00:00:00</td><td id=\"eFControlDataMovieTimecodeContainerFLOAT\">0.0</td>\n";
$content .= "		</tr>\n";
$content .= "		<tr>\n";
$content .= "			<th><div class=\"eFMovieTimecodesContainerHeads\">Meter</div></th><th><div class=\"eFMovieTimecodesContainerHeads\">Feet</div></th>\n";
$content .= "		</tr>\n";
$content .= "		<tr>\n";
$content .= "			<td id=\"eFControlDataMovieTimecodeContainerMETER\">0000</td><td id=\"eFControlDataMovieTimecodeContainerFEET\">0000</td>\n";
$content .= "		</tr>\n";
$content .= "	</table>\n";
$content .= "</div>\n";
$content .= "<!-- /eF Movie Timecodes Container HTML -->\n";
$content .= "</div>\n";
$content .= "<div id=\"eFMovieAnnotationsNewFormContainerWarning\">\n";
$content .= "	<button id=\"eFAFormWarnOKButton\">OK</button>\n";
$content .= "	<div id=\"eFMovieAnnotationsNewFormContainerWarningContent\"></div>\n";
$content .= "</div>\n";
$content .= "<!-- eF Movie Realtions Second Timeline Container HTML -->\n";
$content .= "<div id=\"eFRelMovieTimelineB\">\n";
$content .= "\n";
$content .= "<div id=\"eFMovieControlsContainerSloMoRel\">\n";
$content .= "<div id=\"efMoviePlaybuttonsSloMoChooseRel\" class=\"efMoviePlaybuttonsC\">\n";
$content .= "		<select id=\"eFSloMoSpeedChooserRel\">\n";
$content .= "			<option value=\"1000\">1</option>\n";
$content .= "			<option value=\"500\">2</option>\n";
$content .= "			<option value=\"333\">3</option>\n";
$content .= "			<option value=\"250\">4</option>\n";
$content .= "		</select>\n";
$content .= "	</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsSloMoBRel\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsSloMoFRel\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "<div id=\"eFMovieRangeInputContainerRel\">\n";
$content .= "\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "<div id=\"eFMovieControlsContainerRel\">\n";
$content .= "	<!-- <div id=\"efMoviePlaybuttonsPlayPauseB\" class=\"efMoviePlaybuttons\">&emsp;</div> -->\n";
$content .= "	<div id=\"efMoviePlaybuttonsPlayPauseFRel\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div id=\"efMoviePlaybuttonsStartRel\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	<div id=\"efMoviePlaybuttonsEndRel\" class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons\">&emsp;</div>\n";
$content .= "	\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">6</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">12</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">16</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">18</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">20</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">22</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">24</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">25</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">36</div>\n";
$content .= "	<div class=\"efMoviePlaybuttons efMovieSpeedContainers\">48</div>\n";
$content .= "</div>\n";
$content .= "\n";
$content .= "<div id=\"eFTimelineContainerRel\">\n";
$content .= "	<table class=\"eFTimelineContainerTableRel\" style=\"margin-left: auto; \">\n";
$content .= "		<thead>\n";
$content .= "			<tr id=\"eFTimelineContainerTableFrameNumbersRel\">\n";
$content .= "			<th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>\n";
$content .= "			<th id=\"eFTimelineContainerTableINRel\"><img id=\"efTLCINRel\" alt=\"in\" src=\"_img/in.png\" width=\"18\" height=\"14\"></th><th id=\"eFTimelineContainerTableActualRel\"></th><th id=\"eFTimelineContainerTableOUTRel\"><img id=\"efTLCOUTRel\" alt=\"out\" src=\"_img/out.png\" width=\"18\" height=\"14\"></th>\n";
$content .= "			<th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>\n";
$content .= "			</tr>\n";
$content .= "		</thead>\n";
$content .= "		<tbody>\n";
$content .= "			<tr id=\"eFTimelineContainerTableFramePicsRel\">\n";
$content .= "			<td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			<td colspan=\"3\" id=\"eFTimelineContainerAFrameRel\"><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			<td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td><td><img class=\"null\" alt=\"null\" src=\"_img/null.png\" width=\"78px\" height=\"1px\"></td>\n";
$content .= "			</tr>\n";
$content .= "		</tbody>\n";
$content .= "	</table>\n";
$content .= "</div>\n";
$content .= "</div>\n";
$content .= "</body>\n";
$content .= "</html>\n";

$fp = fopen("index.php", "w");
fwrite($fp, $content);
fclose($fp);

unlink('buildIndex.php');
