<?php
error_reporting(E_ALL);
ini_set('display_errors', 'On');

include 'includes/functions.php';

$databaseName = preg_replace("/[^\w\s\.\-\,_]/","",$_POST['databaseName']) ?: 'eFilms';
$databaseLocation = preg_replace("/[^\w\s\.\-\,_]/","",$_POST['databaseLocation']) ?: 'localhost';
$databaseUsername = preg_replace("/[^\w\s\.\-\,_]/","",$_POST['databaseUsername']);
$databasePassword = preg_replace("/[^\w\s\.\-\,_]/","",$_POST['databasePassword']);

$connection = mysqli_connect( $databaseLocation, $databaseUsername, $databasePassword );
if (!$connection) {
	// no connection, failure of credentials
	$results['complete'] = 'no';
	$results['reason'] = 'MySQL Credentials Failed';
	echo json_encode($results);
	exit();
}

// the connection worked, so let's go ahead and build our database connection file
$content = "<?php\n";
$content .= "\$includes = get_included_files();\n";
$content .= "if (count(\$includes) < 1) {\n";
$content .= "  exit();\n";
$content .= "}\n";
$content .= "\$localDatabase = mysqli_connect('".$databaseLocation."','".$databaseUsername."','".$databasePassword."','".$databaseName."');\n";
$content .= "if (!\$localDatabase) {\n";
$content .= "  echo \"<h2>Service not currently available</h2>\";\n";
$content .= "  header(\"Service Unavailable\", 503);\n";
$content .= "  exit();\n";
$content .= "}\n";
$content .= "ini_set('default_charset','UTF-8');\n";
$content .= "mysqli_set_charset(\$localDatabase, \"utf8\");\n";

$file = fopen(directoryAboveWebRoot()."/db_con.php", "w");
if ($file === false) {
	$results['complete'] = 'no';
	$results['reason'] = 'Can not write a file above the web root folder.';
	echo json_encode($results);
	exit();
}
fwrite($file, $content);
fclose($file);

$structure = "-- phpMyAdmin SQL Dump\n";
$structure .= "-- version 4.0.8\n";
$structure .= "-- http://www.phpmyadmin.net --\n";
$structure .= "-- Host: ipartners.c6csc7ldxwzd.us-east-1.rds.amazonaws.com\n";
$structure .= "-- Generation Time: Apr 21, 2015 at 04:32 PM\n";
$structure .= "-- Server version: 5.6.21-log\n";
$structure .= "-- PHP Version: 5.3.29\n";
$structure .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\"; SET time_zone = \"+00:00\";\n";
$structure .= "--\n";
$structure .= "-- Database: `".$databaseName."`\n";
$structure .= "--\n";
$structure .= "CREATE DATABASE IF NOT EXISTS `efilms` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci; USE `".$databaseName."`;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ActiveFilms` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ActiveFilms` (\n";
$structure .= "`filmNumber` int(3) NOT NULL DEFAULT '0' COMMENT 'Table ID',\n";
$structure .= "`EF-NS` int(3) DEFAULT NULL COMMENT 'Film Number',\n";
$structure .= "`reel` varchar(3) DEFAULT NULL COMMENT 'R## for number in a set of reels',\n";
$structure .= "`source` varchar(5) DEFAULT NULL COMMENT 'Abbreviation for source providing film',\n";
$structure .= "`germanTitle` varchar(105) DEFAULT NULL COMMENT 'Title in German',\n";
$structure .= "`englishTitle` varchar(107) DEFAULT NULL COMMENT 'Title in English',\n";
$structure .= "`year` varchar(9) DEFAULT NULL COMMENT 'Year film was created',\n";
$structure .= "`series` varchar(48) DEFAULT NULL COMMENT 'Film Series Title',\n";
$structure .= "`archivalNumber` varchar(12) DEFAULT NULL COMMENT 'Film Archive Record ID',\n";
$structure .= "`germanGeneration` varchar(20) DEFAULT NULL COMMENT 'Film Generation (German)',\n";
$structure .= "`englishGeneration` varchar(255) DEFAULT NULL COMMENT 'Film Generation (English)',\n";
$structure .= "`germanPosNeg` varchar(16) DEFAULT NULL COMMENT 'Positive or Negative Type (German)',\n";
$structure .= "`englishPosNeg` varchar(255) DEFAULT NULL COMMENT 'Positive or Negative Type (English)',\n";
$structure .= "`germanFilmBase` varchar(18) DEFAULT NULL COMMENT 'Film Base (German)',\n";
$structure .= "`englishFilmBase` varchar(255) DEFAULT NULL COMMENT 'Film Base (English)',\n";
$structure .= "`germanPreviousGenerations` varchar(37) DEFAULT NULL COMMENT 'Pervious Generation if Copy (German)',\n";
$structure .= "`englishPreviousGenerations` varchar(31) DEFAULT NULL COMMENT 'Pervious Generation if Copy (English)',\n";
$structure .= "`originalFilmGauge` varchar(4) DEFAULT NULL COMMENT 'Original Film Gauge',\n";
$structure .= "`farbe` varchar(5) DEFAULT NULL COMMENT 'Color / BW (German)',\n";
$structure .= "`color` varchar(5) DEFAULT NULL COMMENT 'Color / BW (English)',\n";
$structure .= "`ton` varchar(5) DEFAULT NULL COMMENT 'Sound / Mute (German)',\n";
$structure .= "`sound` varchar(5) DEFAULT NULL COMMENT 'Sound / Mute (English)',\n";
$structure .= "`tonverfahren` varchar(18) DEFAULT NULL COMMENT 'Sound Process (German)',\n";
$structure .= "`soundProcess` varchar(10) DEFAULT NULL COMMENT 'Sound Process (English)',\n";
$structure .= "`frames` varchar(6) DEFAULT NULL COMMENT 'Total Frames',\n";
$structure .= "`fps` int(2) DEFAULT NULL COMMENT 'Frames Per Second',\n";
$structure .= "`minutes` varchar(2) DEFAULT NULL COMMENT 'Total Minutes',\n";
$structure .= "`seconds` varchar(2) DEFAULT NULL COMMENT 'Seconds',\n";
$structure .= "`sprache` varchar(7) DEFAULT NULL COMMENT 'Language (German)',\n";
$structure .= "`language` varchar(6) DEFAULT NULL COMMENT 'Language (English)',\n";
$structure .= "`digitalFormat` varchar(3) DEFAULT NULL COMMENT 'Digital Format',\n";
$structure .= "`germanDigitalLab` varchar(25) DEFAULT NULL COMMENT 'Digital Lab (German)',\n";
$structure .= "`englishDigitalLab` varchar(25) DEFAULT NULL COMMENT 'Digital Lab (English)',\n";
$structure .= "`digitalCopyDate` varchar(4) DEFAULT NULL COMMENT 'Date Digital Copy was made',\n";
$structure .= "`germanGenre` varchar(24) DEFAULT NULL COMMENT 'Genre (German)',\n";
$structure .= "`englishGenre` varchar(21) DEFAULT NULL COMMENT 'Genre (English)',\n";
$structure .= "`producer` varchar(12) DEFAULT NULL COMMENT 'Producer Name',\n";
$structure .= "`director` varchar(12) DEFAULT NULL COMMENT 'Director Name',\n";
$structure .= "`cinematography` varchar(21) DEFAULT NULL COMMENT 'Cinematographer',\n";
$structure .= "`collection` varchar(20) DEFAULT NULL COMMENT 'Collection Title',\n";
$structure .= "`provenance` varchar(80) DEFAULT NULL COMMENT 'How film was obtained',\n";
$structure .= "`description` varchar(10) DEFAULT NULL COMMENT 'Description of film',\n";
$structure .= "`isLive` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Is this shown on the website',\n";
$structure .= "`researchLog` longtext COMMENT 'Researcher''s Notes',\n";
$structure .= "PRIMARY KEY (`filmNumber`)\n";
$structure .= ") ENGINE=InnoDB DEFAULT CHARSET=utf8;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_Config_Naming` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_Config_Naming` (\n";
$structure .= "`ID_C_Naming` int(11) NOT NULL COMMENT 'table id',\n";
$structure .= "`_FM_CREATE` varchar(255) NOT NULL COMMENT 'who created the entry',\n";
$structure .= "`_FM_CHANGE` varchar(255) NOT NULL COMMENT 'who edited the entry',\n";
$structure .= "`_FM_DATETIME_CREATE` datetime NOT NULL COMMENT 'when the entry was created',\n";
$structure .= "`_FM_DATETIME_CHANGE` datetime NOT NULL COMMENT 'when the entry was changed',\n";
$structure .= "`eFFormTip` varchar(255) NOT NULL COMMENT 'Type of data entry form',\n";
$structure .= "`List_Entry` varchar(255) NOT NULL COMMENT 'Phrase in German',\n";
$structure .= "`List_Entry_GID` varchar(255) NOT NULL,\n";
$structure .= "`List_Entry_GName` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`visibility` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`List_Entry_EN` varchar(255) NOT NULL COMMENT 'Phrase in English',\n";
$structure .= "PRIMARY KEY (`ID_C_Naming`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_Config_Users` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_Config_Users` (\n";
$structure .= "`ID_C_Users` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`_FM_CREATE` varchar(255) NOT NULL COMMENT 'who created this record',\n";
$structure .= "`_FM_CHANGE` varchar(255) NOT NULL COMMENT 'who edited this record',\n";
$structure .= "`_FM_DATETIME_CREATE` datetime NOT NULL COMMENT 'when was the record created',\n";
$structure .= "`_FM_DATETIME_CHANGE` datetime NOT NULL COMMENT 'when was the record changed',\n";
$structure .= "`USER_Name` varchar(255) NOT NULL COMMENT 'user''s name',\n";
$structure .= "`USER_Nik` varchar(255) NOT NULL COMMENT 'user''s nickname',\n";
$structure .= "`USER_Rights` varchar(255) NOT NULL COMMENT 'not used',\n";
$structure .= "`USER_Pass` varchar(255) NOT NULL COMMENT 'Unused, handled by server',\n";
$structure .= "`RIGHTS_Config` enum('NONE','VIEW','SELFEDIT','EDIT') NOT NULL DEFAULT 'NONE' COMMENT 'can edit config options (''NONE'',''VIEW'',''SELFEDIT'',''EDIT'')',\n";
$structure .= "`RIGHTS_Resources` enum('NONE','VIEW','SELFEDIT','EDIT') NOT NULL DEFAULT 'NONE' COMMENT 'can edit resources options (''NONE'',''VIEW'',''SELFEDIT'',''EDIT'')',\n";
$structure .= "`RIGHTS_Publish` enum('NONE','VIEW','SELFEDIT','EDIT') NOT NULL DEFAULT 'NONE' COMMENT 'can edit publish options (''NONE'',''VIEW'',''SELFEDIT'',''EDIT'')',\n";
$structure .= "`email` varchar(255) NOT NULL COMMENT 'user''s email for password resets', PRIMARY KEY (`ID_C_Users`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_Config_Users_MovieRights` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_Config_Users_MovieRights` (\n";
$structure .= "`ID_C_Users_MovieRights` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`_FM_CREATE` varchar(255) NOT NULL COMMENT 'who created the record',\n";
$structure .= "`_FM_CHANGE` varchar(255) NOT NULL COMMENT 'who edited the record',\n";
$structure .= "`_FM_DATETIME_CREATE` datetime NOT NULL COMMENT 'when the record was created',\n";
$structure .= "`_FM_DATETIME_CHANGE` datetime NOT NULL COMMENT 'when the record was changed',\n";
$structure .= "`ID_C_Users` int(11) NOT NULL COMMENT 'user table id value',\n";
$structure .= "`ID_Movies` int(11) NOT NULL COMMENT 'movie table id value',\n";
$structure .= "`RIGHTS_Movies` enum('NONE','VIEW','SELFEDIT','EDIT') NOT NULL DEFAULT 'NONE' COMMENT 'rights to edit annotations\n";
$structure .= "(''NONE'',''VIEW'',''SELFEDIT'',''EDIT'')',\n";
$structure .= "PRIMARY KEY (`ID_C_Users_MovieRights`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_Content_Movies` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_Content_Movies` (\n";
$structure .= "`ID_Movies` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`FILM_ID` varchar(255) NOT NULL COMMENT 'complete film id',\n";
$structure .= "`STAMMDATEN_Archivsignatur` varchar(255) NOT NULL COMMENT 'archival number',\n";
$structure .= "`STAMMDATEN_Format` varchar(255) DEFAULT NULL COMMENT 'original film format',\n";
$structure .= "`STAMMDATEN_Displaytitel` text COMMENT 'display title',\n";
$structure .= "`_eFWEB_Praktikantin` int(1) NOT NULL COMMENT 'unused',\n";
$structure .= "`_eFWEB_EditorV` int(1) NOT NULL COMMENT 'display in the editor',\n";
$structure .= "`_eFWEB_FPS` int(2) NOT NULL COMMENT 'frames per second default for the editor',\n";
$structure .= "`_eFWEB_Status` int(1) DEFAULT '0' COMMENT '0 ... unbearbeitet, 1 ... PraktikantIn arbeitet, 2 ... PraktikantIn abgeschlossen', `_eFWEB_Speed` int(2) DEFAULT NULL COMMENT 'frames per second default for the editor',\n";
$structure .= "`_eFWEB_POnline` int(1) DEFAULT '0' COMMENT 'unused',\n";
$structure .= "`DESCRIPTION_DE` text COMMENT 'unused',\n";
$structure .= "`DESCRIPTION_EN` text COMMENT 'unused',\n";
$structure .= "`TITLE_EN` text COMMENT 'unused',\n";
$structure .= "PRIMARY KEY (`ID_Movies`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_Content_Movies_Annotations` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_Content_Movies_Annotations` (\n";
$structure .= "`ID_Movies` int(11) NOT NULL COMMENT 'movie table id',\n";
$structure .= "`ID_Annotations` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`_FM_CREATE` varchar(255) NOT NULL COMMENT 'who created the record',\n";
$structure .= "`_FM_CHANGE` varchar(255) NOT NULL COMMENT 'who edited the recored',\n";
$structure .= "`_FM_DATETIME_CREATE` datetime NOT NULL COMMENT 'when was the record created',\n";
$structure .= "`_FM_DATETIME_CHANGE` datetime NOT NULL COMMENT 'when was the record modified',\n";
$structure .= "`eF_FILM_ID` varchar(255) NOT NULL COMMENT 'full film id',\n";
$structure .= "`FormID` varchar(255) NOT NULL COMMENT 'editor form id that was used to create this value',\n";
$structure .= "`AnnotationType_L1` varchar(255) NOT NULL,\n";
$structure .= "`AnnotationType_L2` varchar(255) NOT NULL,\n";
$structure .= "`AnnotationType_L3` varchar(255) NOT NULL,\n";
$structure .= "\n";
$structure .= "`startTime` int(11) NOT NULL COMMENT 'start frame',\n";
$structure .= "`endTime` int(11) NOT NULL COMMENT 'end frame',\n";
$structure .= "`timeAnnotation` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`source` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`source_from` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`source_to` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`ref` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`version` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`annotation` varchar(255) NOT NULL COMMENT 'text value',\n";
$structure .= "`coverage` varchar(255) NOT NULL COMMENT 'location value',\n";
$structure .= "`coverageType` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`coverage_S_Longitude` varchar(255) NOT NULL COMMENT 'longitude',\n";
$structure .= "`coverage_S_Latitude` varchar(255) NOT NULL COMMENT 'latitude',\n";
$structure .= "`coverage_S_Geoname` varchar(255) NOT NULL COMMENT 'location name',\n";
$structure .= "`coverage_S_LandmarkID` varchar(255) NOT NULL COMMENT 'resource id value for landmark',\n";
$structure .= "`coverage_T_From` varchar(255) NOT NULL COMMENT 'year-month',\n";
$structure .= "`coverage_T_To` varchar(255) NOT NULL COMMENT 'year-month',\n";
$structure .= "`subject` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`subjectType` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`subject_P_PersonName` varchar(255) NOT NULL COMMENT 'identified person''s name',\n";
$structure .= "`subject_P_PersonID` varchar(255) NOT NULL COMMENT 'resource id of person',\n";
$structure .= "`subject_O_OrganizationType` varchar(255) NOT NULL COMMENT 'type of identified organization',\n";
$structure .= "`subject_O_OrganizationName` varchar(255) NOT NULL COMMENT 'name of identified organization',\n";
$structure .= "`subject_O_OrganizationID` varchar(255) NOT NULL COMMENT 'resource id for organization',\n";
$structure .= "`subject_HE_Title` varchar(255) NOT NULL COMMENT 'historic event title',\n";
$structure .= "`subject_HE_Date` varchar(255) NOT NULL COMMENT 'historic event date',\n";
$structure .= "`subject_HE_Type` varchar(255) NOT NULL COMMENT 'historic event type',\n";
$structure .= "`subject_HE_ID` varchar(255) NOT NULL COMMENT 'resource id for historic event',\n";
$structure .= "`language` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`relation` varchar(255) NOT NULL COMMENT 'image file, movie',\n";
$structure .= "`relation_relationType` varchar(255) NOT NULL,\n";
$structure .= "`relation_relationIdentifier` varchar(255) NOT NULL COMMENT 'L1 object key',\n";
$structure .= "`relation_relationIdentifier_from` varchar(255) NOT NULL COMMENT 'frame number',\n";
$structure .= "`relation_relationIdentifier_to` varchar(255) NOT NULL COMMENT 'frame number',\n";
$structure .= "`relation_relationIdentifier_source` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`relation_relationIdentifier_ref` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`relation_relationIdentifier_version` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`relation_relationIdentifier_annotation` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description` text NOT NULL COMMENT 'text content',\n";
$structure .= "`description_descriptionType` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_descriptionTypeSource` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_descriptionTypeRef` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_descriptionTypeVersion` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_descriptionTypeAnnotation` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_segmentType` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_segmentTypeSource` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_segmentTypeRef` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_segmentTypeVersion` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`description_segmentTypeAnnotation` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`_empty` varchar(255) NOT NULL COMMENT 'unused',\n";
$structure .= "`_f_sorter` varchar(255) NOT NULL COMMENT 'sort priority',\n";
$structure .= "`_USER_INPUT` varchar(255) NOT NULL DEFAULT 'source_from' COMMENT 'user nickname',\n";
$structure .= "`researchLog` longtext NOT NULL COMMENT 'research notes',\n";
$structure .= "PRIMARY KEY (`ID_Annotations`),\n";
$structure .= "FULLTEXT KEY `description` (`description`),\n";
$structure .= "FULLTEXT KEY `coverage` (`coverage`),\n";
$structure .= "FULLTEXT KEY `subject_O_OrganizationName` (`subject_O_OrganizationName`),\n";
$structure .= "FULLTEXT KEY `coverage_S_Geoname` (`coverage_S_Geoname`),\n";
$structure .= "FULLTEXT KEY `subject_P_PersonName` (`subject_P_PersonName`),\n";
$structure .= "FULLTEXT KEY `coverage_T_From` (`coverage_T_From`),\n";
$structure .= "\n";
$structure .= "FULLTEXT KEY `coverage_T_To` (`coverage_T_To`),\n";
$structure .= "FULLTEXT KEY `subject_HE_Title` (`subject_HE_Title`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ReSources_HistoricEvents` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ReSources_HistoricEvents` (\n";
$structure .= "`ID_HistoricEvents` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`ST_Title` varchar(255) DEFAULT NULL COMMENT 'title',\n";
$structure .= "`ST_Description` varchar(255) DEFAULT NULL COMMENT 'description',\n";
$structure .= "`ST_StartDate` date DEFAULT NULL COMMENT 'date',\n";
$structure .= "`ST_EndDate` date DEFAULT NULL COMMENT 'date',\n";
$structure .= "PRIMARY KEY (`ID_HistoricEvents`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ReSources_L1` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ReSources_L1` (\n";
$structure .= "`ID_R_L1` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`Type` varchar(255) DEFAULT NULL COMMENT 'Type of Content: Publication, Photo, Event, etc.',\n";
$structure .= "`Object_Key` varchar(255) DEFAULT NULL COMMENT 'The key value for this resource: RES_PUB_#, COV_LMK_#, etc.',\n";
$structure .= "`Category` varchar(255) DEFAULT NULL COMMENT 'Category Name: Resource, Subject, Coverage, etc.',\n";
$structure .= "`Group` varchar(255) DEFAULT NULL COMMENT 'Title of the Group for this resource',\n";
$structure .= "PRIMARY KEY (`ID_R_L1`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ReSources_L2` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ReSources_L2` (\n";
$structure .= "`ID_R_L2` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`ID_R_L1` int(11) DEFAULT NULL COMMENT 'table index from eFilm_ReSources_L1',\n";
$structure .= "`Fieldname` varchar(255) DEFAULT NULL COMMENT 'Title, Publisher, Date(s), etc.',\n";
$structure .= "`Fieldtype` varchar(255) DEFAULT NULL COMMENT 'text, pdf, image',\n";
$structure .= "`Fieldcontent` text COMMENT 'text content or file name if this is an image or PDF',\n";
$structure .= "`originalName` text COMMENT 'For PDF and Images only, original file name',\n";
$structure .= "PRIMARY KEY (`ID_R_L2`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ReSources_RelationIndex` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ReSources_RelationIndex` (\n";
$structure .= "`ID_R_RelationIndex` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`RelationType` varchar(255) DEFAULT NULL COMMENT 'type',\n";
$structure .= "`RelationRemark` text COMMENT 'comment',\n";
$structure .= "`ID_R_L1_A` int(11) DEFAULT NULL COMMENT 'first L1 id',\n";
$structure .= "\n";
$structure .= "`ID_R_L1_B` int(11) DEFAULT NULL COMMENT 'second L1 id',\n";
$structure .= "`ID_Annotations` int(11) DEFAULT NULL COMMENT 'annotation id',\n";
$structure .= "PRIMARY KEY (`ID_R_RelationIndex`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";
$structure .= "-- -------------------------------------------------------- --\n";
$structure .= "-- Table structure for table `eFilm_ReSources_Templates` --\n";
$structure .= "CREATE TABLE IF NOT EXISTS `eFilm_ReSources_Templates` (\n";
$structure .= "`ID_R_Templates` int(11) NOT NULL AUTO_INCREMENT COMMENT 'table id',\n";
$structure .= "`Resource_Type` varchar(255) DEFAULT NULL COMMENT 'resource type',\n";
$structure .= "`Resource_Field` varchar(255) DEFAULT NULL COMMENT 'form field name',\n";
$structure .= "`Resource_Fieldtype` varchar(255) DEFAULT NULL COMMENT 'form field type',\n";
$structure .= "`Resource_Index` int(11) DEFAULT NULL COMMENT 'field sort order',\n";
$structure .= "PRIMARY KEY (`ID_R_Templates`)\n";
$structure .= ") ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;\n";

$localDatabase = mysqli_connect($databaseLocation, $databaseUsername, $databasePassword);
mysqli_multi_query($localDatabase, $structure);
mysqli_close($localDatabase);

$results['complete'] = 'yes';
$results['setting'] = 'database';
$results['reason'] = 'Your database setup is complete!';
echo json_encode($results);

unlink('makeDatabase.php');
