<?php
$language = (isset($_COOKIE["language"]) ? $_COOKIE["language"] : "en");
echo "<div style='padding: 5px 10px; background-color: rgb(204, 204, 204); width: 250px; margin:10px 10px;'>";
switch ($language) {
        case "de":
            echo "<p><strong>BILDZÄHLER:</strong><br>Die Zahl im Bildzähler korrespondiert mit der Nummer des Einzelbildes (Kader, Frame) das oberhalb erscheint und mit der Nummer des Einzelbildes im originalen analogen Film. Film Amateuraufnahmen Wien, Frühjahr 1938 z.B. reicht von 0 (Anfang des Films) bis 9882 (Ende des Films). Verwenden Sie den Bildzähler, um die Nummer des Einzelbildes einzugeben, zu dem Sie springen wollen. Verwenden Sie den Bildzähler auch, um den Film mit den Pfeiltasten auf Ihrem Keyboard Bild für Bild vorwärts und rückwärts abzuspielen.</p>";
            echo "<p><strong>TIME CODE:</strong><br>Der SMPTE Time Code zeigt Stunden:Minuten:Sekunden;Frame-Nummer (HH:MM:SS;FF) korrespondierend zum abgespielten Film. </p>";
            echo "<p><strong>BILDRATE:</strong><br>Filme starten automatisch mit der Bildrate (Frame Rate), die der Kameramann verwendet hat, als der Film in den 1930er Jahren gedreht wurde. Wenn diese Information fehlt, starten sie mit der wahrscheinlich verwendeten Bildrate, basierend auf dem verwendeten Filmformat. Der Film-Player erlaubt den Usern, die Geschwindigkeit (die Bildrate) individuell anzupassen, von langsam (6 Bilder pro Sekunde, kurz: fps für Frames-Per-Second) bis schnell (36 fps). Um die Bildrate zu ändern, wählen Sie eine Nummer – 6, 12, 16, 18, 20, 22, 24, 25, 36 –unten rechts im Film-Player (die gewählte Geschwindigkeit wird blau markiert) und klicken Sie auf den Play-Button. Sie können zwischen den Bildraten hin und her wechseln, während der Film läuft.</p>";
            echo "<p><strong>DIESEN FILM DURCHSUCHEN:</strong><br>Verwenden Sie diesen Button, um bestimmte Einstellungen oder sogar Einzelbilder innerhalb eines Filmes zu finden. Um mehrere oder alle Filme zu durchsuchen, verwenden Sie das Schnellsuchfeld oder klicken Sie auf Erweiterte Suche. </p>";
            echo "<p><strong>FILM-PLAYER KURZANLEITUNG:</strong><br>Klicken Sie auf diesen Button, um Tips für die Verwendung des Film-Players zu erhalten, u.a. wie die Geschwindigkeit (die Bildrate) geändert und ein Bild vergrößert werden kann.</p>";
            echo "<p><strong>IMAGE:</strong><br>Gegenwartsfotos der Schauplätze oder andere mit den Filmbildern verbundene Abbildungen werden in der rechten unteren Ecke des Film-Players angezeigt, während der Film läuft. Mittels Mouseover können Sie diese kleinen Bilder vergrößern und über die historischen Filmbilder im Film-Player legen. </p>";
            echo "<p><strong>LANDKARTE:</strong><br>Eine aktuelle Karte mit dem geographischen Ort, der gerade im Film zu sehen ist, wird in der unteren rechten Ecke des Film-Players angezeigt.</p>";
            break;
        default:
            echo "<p><strong>FRAME COUNTER:</strong><br>The number in the frame counter corresponds to the number of the individual frame in the original analog film. For example, film \"Amateur Shots in Vienna, Spring 1938\" ranges from 0 (beginning of film) to 9882 (end of film). Use the frame counter to move forward and backward frame by frame with the arrow keys of your keyboard, or type in the number of the frame you want to jump to. When the film is paused, the gray box under the film player displays the number of the frame that appears above.</p>";
            echo "<p><strong>TIME CODE:</strong><br>The SMPTE time code displays hours: minutes: seconds: frame (HH:MM:SS:FF) corresponding to the film being played.</p>";
            echo "<p><strong>FRAME RATE:</strong><br>Films automatically play in the frame rate the cameraperson used when filming the sequence in the 1930s or, if this information is unavailable, the most likely speed based on the film gauge. This film player allows the user to select a choice of film speed (frame rate) ranging from slow (6 frames-per-second or fps) to fast (36 fps). To change the frame rate, choose a number – 6, 12, 16, 18, 20, 22, 24, 25, 36 – in the bottom right of the film player (the selected speed turns blue) and press the play button. You can toggle between frame rates as the film plays.</p>";
            echo "<p><strong>FILM INFO:</strong><br>The Film Info button displays basic data about the film, including archival source, collection title, provenance, and original film format.</p>";
            echo "<p><strong>SEARCH THIS FILM:</strong><br>Use this button to find specific shots within an individual film. To search across several films, use the Search box or click on Advanced Search at the top of the page.</p>";
            echo "<p><strong>PLAYER HOW-TO:</strong><br>Click this button to see tips for using the film player, including how to change the frame rate and enlarge an image.</p>";
            echo "<p><strong>IMAGE:</strong><br>Modern-day photographs or other related imagery display in the lower left corner of the data window as the historical film plays. Mouse over the image for an expanded view transposed over the historical image in the film player.</p>";
            echo "<p><strong>MAP:</strong><br>A modern-day map with the geographic location appearing in the historical film displays in the lower right corner of the film player.</p>";
            break;
}
echo "</div>";
?>